export const dummyCategories = [
  {
    id: '1',
    name: 'Boarding',
    icon: 'house.fill',
  },
  {
    id: '2',
    name: 'Walking',
    icon: 'figure.walk',
  },
  {
    id: '3',
    name: 'Daycare',
    icon: 'sun.max.fill',
  },
  {
    id: '4',
    name: 'Grooming',
    icon: 'scissors',
  },
  {
    id: '5',
    name: 'Training',
    icon: 'graduationcap.fill',
  },
  {
    id: '6',
    name: 'Vets',
    icon: 'cross.case.fill',
  },
];

export const dummyHosts = [
  {
    id: '1',
    name: 'Sarah Johnson',
    rating: 4.9,
    reviewCount: 124,
    location: 'Brooklyn, NY',
    price: 35,
    services: ['Walking', 'Daycare', 'Boarding'],
    image: 'https://placecats.com/400/350',
    gallery: [
      'https://placecats.com/400/350',
      'https://placecats.com/400/400',
      'https://placecats.com/400/300',
    ],
    about: "Hi, I'm Sarah! I've been a pet lover my whole life. I have a spacious backyard and a friendly Golden Retriever named Max. I specialize in active dogs who need lots of exercise and play time.",
    verified: true,
  },
  {
    id: '2',
    name: 'David Miller',
    rating: 4.7,
    reviewCount: 89,
    location: 'Queens, NY',
    price: 28,
    services: ['Walking', 'Daycare'],
    image: 'https://placedog.net/500/300',
    gallery: [
      'https://placedog.net/500/300',
      'https://placedog.net/400/300',
      'https://placedog.net/300/300',
    ],
    about: "Professional dog walker with 5 years of experience. I know all the best parks in Queens and love taking dogs on adventures.",
    verified: true,
  },
  {
    id: '3',
    name: 'Emma Wilson',
    rating: 4.8,
    reviewCount: 56,
    location: 'Manhattan, NY',
    price: 40,
    services: ['Boarding', 'Grooming'],
    image: 'https://placecats.com/350/250',
    gallery: [
      'https://placecats.com/350/250',
      'https://placecats.com/300/250',
      'https://placecats.com/400/250',
    ],
    about: "I offer a calm and cozy environment for your cats. I'm also a certified groomer, so your furry friend can come home looking their best!",
    verified: false,
  },
  {
    id: '4',
    name: 'Liam Davis',
    rating: 4.6,
    reviewCount: 32,
    location: 'Bronx, NY',
    price: 25,
    services: ['Walking'],
    image: 'https://placedog.net/400/250',
    gallery: [
      'https://placedog.net/400/250',
      'https://placedog.net/300/250',
    ],
    about: "Energetic and reliable dog walker. I'm available for early morning and late evening walks.",
    verified: true,
  },
  {
    id: '5',
    name: 'Olivia Brown',
    rating: 5.0,
    reviewCount: 15,
    location: 'Staten Island, NY',
    price: 32,
    services: ['Daycare', 'Boarding', 'Walking'],
    image: 'https://placecats.com/400/300',
    gallery: [
      'https://placecats.com/400/300',
      'https://placecats.com/300/300',
    ],
    about: "New to the app but experienced with pets! I have a large home with plenty of space for your pets to roam.",
    verified: true,
  },
];